---
title: 关于AdonisJs
permalink: about
category: introduction
---
= 关于AdonisJs

toc::[]

AdonisJs是在所有操作系统上运行的Node.js MVC框架。它提供了一个稳定的生态系统来编写一个服务器端的Web应用程序，以便您可以专注于业务需求，以确定哪个软件包可供选择。

AdonisJs通过一致且富有表现力的API来构建一个完整的Web应用程序或一个微型API服务器，同时保持开发愉悦感。

== 入门
使用AdonisJs并不需要复杂的前置条件，但对熟悉基本的JavaScript、理解异步编程和Node.js将会很有帮助。

此外，请确保阅读 link:installation[安装] 指南， 特别是如果这是你第一次使用AdonisJs的话。

== 其他资源
这里有一些其他地方可以找到关于AdonisJs的信息。

1. link:https://forum.adonisjs.com[官方论坛, window="_blank"], 在这里我们讨论AdonisJs从修复错误到讨论新功能的所有内容。
2. Twitter
3. Github
4. 如果你喜欢这个项目，那么请考虑在 link:https://www.patreon.com/adonisframework[patreon, window="_blank"] 上支持我们.

== Providers
AdonisJs是一个由多个Service Providers组成的模块化框架。Service Providers是AdonisJs应用程序的基石。

从理论上讲，它们就像任何其他npm模块一样，通过一些代码可以与AdonisJs应用程序无缝衔接。例如： link:https://github.com/adonisjs/adonis-bodyparser[BodyParser] 用来解析HTTP请求体 或者 SQL ORM link:https://github.com/adonisjs/adonis-lucid[Lucid] .

== FAQ's
下面是常见问题列表，如果您认为列表中缺少常见问题。请创建一个issue link:https://github.com/adonisjs/docs[点击这里]

[ol-spaced]
1. *AdonisJs与Express或Koa有什么不同？*
+
Express和Koa在路由库之上有一层中间件。当你的项目开始增长的时候，需要分解成好几个用例。
+
而且，雇用一个人变得更难，因为你的项目有自己的标准和惯例。而AdonisJs遵循一套标准化的约定，使雇用人员更容易，使他们在现有的AdonisJs应用程序上工作。

2. *AdonisJs是单一的应用程序？*
+
AdonisJs作为一个框架是多个软件包的组合，与您的应用程序的其他部分完美地集成在一起。
+
该框架提供了一个强大的*依赖注入*层，所有官方和第三方包提供了功能，无需手动连接应用程序的每个部分。
